# Generated by Django 5.2.2 on 2025-06-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='cart',
        ),
        migrations.AddField(
            model_name='bill',
            name='cart',
            field=models.ManyToManyField(to='shop.cart', verbose_name='Корзина'),
        ),
    ]
